### ISSUE TITLE
ERROR: testOpExportSlot.TestOpExportSlot.testBasic_Dvid

### ISSUE THREAD

**Issue by jakirkham** [ilastik/lazyflow#172]
This test is currently failing with an error. It appears `internalOutput` doesn't have a `dtype` in `meta`. Not sure how this could happen. As it is an error in testing `DVID`, maybe @stuarteberg has some insight. Traceback below.

    Traceback (most recent call last):
      File "/xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.2.1-py2.7.egg/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/xopt_ilastik/local/src/ilastik/lazyflow/tests/testOpExportSlot.py", line 144, in testBasic_Dvid
        opRead.FilePath.setValue( opExport.ExportPath.value )
      File "/xopt_ilastik/local/src/ilastik/lazyflow/lazyflow/slot.py", line 110, in call_in_setup_context
        return func(self, *args, **kwargs)
      File "/xopt_ilastik/local/src/ilastik/lazyflow/lazyflow/slot.py", line 1134, in setValue
        self._changed()
      File "/xopt_ilastik/local/src/ilastik/lazyflow/lazyflow/slot.py", line 1335, in _changed
        self._configureOperator(self)
      File "/xopt_ilastik/local/src/ilastik/lazyflow/lazyflow/slot.py", line 1349, in _configureOperator
        self.operator._setupOutputs()
      File "/xopt_ilastik/local/src/ilastik/lazyflow/lazyflow/operator.py", line 450, in _setupOutputs
        self.setupOutputs()
      File "/xopt_ilastik/local/src/ilastik/lazyflow/lazyflow/operators/ioOperators/opInputDataReader.py", line 157, in setupOutputs
        ram_per_pixel = self.internalOutput.meta.dtype().nbytes
    TypeError: 'NoneType' object is not callable

**Comment by jakirkham** [comment]
The error appeared between these two commits ( https://github.com/ilastik/lazyflow/commit/85312d8812a485d9fc62618223f532cac6258219 ) and ( https://github.com/ilastik/lazyflow/commit/e5b5c3625e9ffa0878dd546f85ff07de96640b4b ).

**Comment by stuarteberg** [comment]
This bug was introduced via c832c82aeb314d32365e5729affa87a28b21da7c, now fixed via 1826e5d81b8568a0710dfba4d6f3d728bba16e38

**Comment by jakirkham** [comment]
Yep, that appears to fix it.
