### ISSUE TITLE
TestOpCompressedUserLabelArray.testEraseAll -- FAIL: Test behavior when all labels of a particular class are erased.

### ISSUE THREAD

**Issue by jakirkham** [ilastik/lazyflow#177]
======================================================================
FAIL: Check that some labels can be deleted correctly from the sparse array.
----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.2.1-py2.7.egg/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/xopt_ilastik/local/src/ilastik/lazyflow/tests/testOpCompressedUserLabelArray.py", line 176, in testEraser
        assert (outputData[...] == expectedOutput[...]).all()
    AssertionError: 
    -------------------- >> begin captured logging << --------------------
    lazyflow.operators.opCompressedCache: DEBUG: desired space: 25000.0
    lazyflow.operators.opCompressedCache: DEBUG: blockshape space: 1000.0
    lazyflow.operators.opCompressedCache: DEBUG: factor: 0.341995189335
    lazyflow.operators.opCompressedCache: DEBUG: Using chunk shape: (1, 10, 10, 10, 1)
    lazyflow.operators.opCompressedCache: DEBUG: desired space: 100000.0
    lazyflow.operators.opCompressedCache: DEBUG: blockshape space: 1000.0
    lazyflow.operators.opCompressedCache: DEBUG: factor: 0.215443469003
    lazyflow.operators.opCompressedCache: DEBUG: Using chunk shape: (1, 10, 10, 10, 1)
    lazyflow.operators.opCompressedCache: DEBUG: desired space: 100000.0
    lazyflow.operators.opCompressedCache: DEBUG: blockshape space: 1000.0
    lazyflow.operators.opCompressedCache: DEBUG: factor: 0.215443469003
    lazyflow.operators.opCompressedCache: DEBUG: Using chunk shape: (1, 10, 10, 10, 1)
    lazyflow.operators.opCompressedCache: DEBUG: Copying data INTO 8 blocks...
    lazyflow.operators.opCompressedCache: DEBUG: Creating a cache file for block: [0, 0, 0, 0, 0]
    lazyflow.operators.opCompressedCache: DEBUG: Creating a cache file for block: [0, 0, 10, 0, 0]
    lazyflow.operators.opCompressedCache: DEBUG: Creating a cache file for block: [0, 0, 20, 0, 0]
    lazyflow.operators.opCompressedCache: DEBUG: Creating a cache file for block: [0, 0, 30, 0, 0]
    lazyflow.operators.opCompressedCache: DEBUG: Creating a cache file for block: [0, 10, 0, 0, 0]
    lazyflow.operators.opCompressedCache: DEBUG: Creating a cache file for block: [0, 10, 10, 0, 0]
    lazyflow.operators.opCompressedCache: DEBUG: Creating a cache file for block: [0, 10, 20, 0, 0]
    lazyflow.operators.opCompressedCache: DEBUG: Creating a cache file for block: [0, 10, 30, 0, 0]
    lazyflow.operators.opCompressedCache: DEBUG: Copying data INTO 4 blocks...
    --------------------- >> end captured logging << ---------------------

**Comment by jakirkham** [comment]
Failure appears in-between commits ( 96278e7..902e232 ).
